// LOGGER CONSTANTS
export const DATABASE_LOGGER = 'DATABASE'
export const ADD_USE_CASE_LOGGER = 'ADD_USE_CASE'
export const GET_ALL_USE_CASE_LOGGER = 'GET_ALL_USE_CASE'
export const CHANGE_NAME_USE_CASE_LOGGER = 'CHANGE_NAME_USE_CASE'
export const EXPRESS_API_LOGGER = 'EXPRESS_API'

// PUBSUB CONSTANTS
export const EXAMPLE_CREATED_EVENT = 'EXAMPLE_CREATED'
